package ru.stqa.pft.adressbook;

// Generated by Selenium IDE
import org.junit.Test;
public class GroupDeletionTests extends TestBase{
  @Test
  public void testGroupDeletion() {
    gotoGroupPage();
    selectGroup();
    deleteSelectedGroups();
    returnToGroupPage();
  }
}
