package ru.stqa.pft.adressbook.tests;

import java.util.List;

import org.junit.Assert;
// Generated by Selenium IDE
import org.junit.Test;

import ru.stqa.pft.adressbook.model.GroupData;

public class GroupDeletionTests extends TestBase {
	@Test
	public void testGroupDeletion() {
		app.getNavigationHelper().gotoGroupPage();

		if (!app.getGrouphelper().isThereAGroup()) {
			app.getGrouphelper().createGroup(new GroupData("test1", null, null));
		}
		List<GroupData> before = app.getGrouphelper().getGroupList();
		app.getGrouphelper().selectGroup(before.size() - 1);
		app.getGrouphelper().deleteSelectedGroups();
		app.getGrouphelper().returnToGroupPage();
		List<GroupData> after = app.getGrouphelper().getGroupList();
		Assert.assertTrue(after.size() == before.size() - 1);

		before.remove(before.size() - 1);
		Assert.assertEquals(before, after);
	}
}
