package ru.stqa.pft.adressbook.tests;

import java.util.List;

import org.junit.Assert;
// Generated by Selenium IDE
import org.junit.Test;

import ru.stqa.pft.adressbook.model.GroupData;

public class GroupCreationTests extends TestBase {
	@Test
	public void testGroupCreation() {

		app.getNavigationHelper().gotoGroupPage();
		List <GroupData> before = app.getGrouphelper().getGroupList();
		app.getGrouphelper().createGroup(new GroupData("test1", null, null));
		
		List<GroupData> after = app.getGrouphelper().getGroupList();


		Assert.assertTrue(after.size() == before.size() + 1);
//		System.out.println("before: " + before + " | after " + after);

	}
}
