package ru.stqa.pft.adressbook.tests;

// Generated by Selenium IDE
import org.junit.Test;

import ru.stqa.pft.adressbook.model.GroupData;

public class GroupDeletionTests extends TestBase {
	@Test
	public void testGroupDeletion() {
		app.getNavigationHelper().gotoGroupPage();
		if (!app.getGrouphelper().isThereAGroup()) {
			app.getGrouphelper().createGroup(new GroupData("test1", null, null));
		}
		app.getGrouphelper().selectGroup();
		app.getGrouphelper().deleteSelectedGroups();
		app.getGrouphelper().returnToGroupPage();
	}
}
