package ru.stqa.pft.adressbook.tests;

// Generated by Selenium IDE
import org.junit.Test;
public class GroupDeletionTests extends TestBase{
  @Test
  public void testGroupDeletion() {
    app.getNavigationHelper().gotoGroupPage();
    app.getGrouphelper().selectGroup();
    app.getGrouphelper().deleteSelectedGroups();
    app.getGrouphelper().returnToGroupPage();
  }
}
